In [1]:
from __future__ import print_function
import torch

Costruct 5/3 matrix unitialized

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-8.4753e-13,  4.5765e-41, -2.0527e+12],
        [ 3.0964e-41,  6.3010e-36,  6.3010e-36],
        [ 6.3010e-36,  6.3010e-36,  2.6428e-29],
        [ 1.6131e-33,  6.3010e-36,  6.3010e-36],
        [ 6.3010e-36,  6.3010e-36,  6.3010e-36]])


Construct randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8116, 0.2417, 0.7737],
        [0.8611, 0.9092, 0.8723],
        [0.2907, 0.6688, 0.7274],
        [0.5679, 0.7463, 0.8811],
        [0.1452, 0.6525, 0.0145]])


Construct matrix initialized with zeros

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## Operations

### Addition:

In [5]:
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x + y)

tensor([[1.1103, 0.5511, 0.3068],
        [1.3254, 0.9567, 0.8741],
        [0.8068, 0.6089, 1.0901],
        [1.2008, 1.4161, 0.6517],
        [0.2403, 0.4097, 0.9439]])


In [6]:
print(torch.add(x,y))

tensor([[1.1103, 0.5511, 0.3068],
        [1.3254, 0.9567, 0.8741],
        [0.8068, 0.6089, 1.0901],
        [1.2008, 1.4161, 0.6517],
        [0.2403, 0.4097, 0.9439]])


In [7]:
print(x[:1])

tensor([[0.3049, 0.4732, 0.0308]])


Resizing the tensors

In [9]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


get number from 1 item torch

In [11]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6207])
-0.6207107305526733


CUDA tensors

In [22]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("CUDA cores not available")

CUDA cores not available
